# https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

# github: [vindarel,] # we can put 4 handles here.
# we can only put 1 handle below:
ko_fi: vindarel
liberapay: vindarel
patreon: vindarel
# and again, up to 4 custom links:
# custom: [link1, …, link4]
